### ISSUE TITLE
About half the files are falsely flagged as being in "files in zotfile directory but not in DB"

### ISSUE THREAD

**Issue by roey-angel** [giorginolab/zotfile_doctor#1]
Flagging files in DB but not in zotfile dir seems to work well, but the other way around it flags about half the files in the zotfile directory but not in the DB.
I checked about 10 of those and they are all in the DB and link properly to the file.

**Comment by tonigi** [comment]
May be a matter of relative vs absolute path in Zotero? 
Or files which have not been renamed by zotfile.

**Comment by roey-angel** [comment]
Thanks!
Indeed most cases were files with absolute rather than relative paths.
However, it looks like the tool also wrongly reports non-PDF files (e.g. doc, ppt etc.) as being missing in the zotfile directory, despite being there and with a relative path.

**Comment by tonigi** [comment]
Yes. Absolute paths may be fixed in the future (there is a pull request).

Non-pdf (also affects capitalizations like Pdf) are a known bug. I'd prefer to just ignore them, but they should be ignored in both places.

**Comment by tonigi** [comment]
Can you please test again? Thanks

**Comment by roey-angel** [comment]
Do you mean the absolute/relative path issue?
Yes, I  confirmed it. 
I ran Manage Attachments -> Rename Attachments on all entries and then zotfile_doctor again and it ran just fine (i.e. no false flagging of files in the zotfile directory but not in the DB).

**Comment by tonigi** [comment]
I mean that     c245100a8e8a8f9a3387108e4fd1ba7a704f8f22 may work with absolute paths too thanks to @vancleve . Also should't mark errors for docx etc any longer. However I think "rename all" is the correct way to keep the db.

**Comment by roey-angel** [comment]
cannot test for absolute paths anymore (none left in my DB) but the new version doesn't flag doc files anymore
