### ISSUE TITLE
Could you add support to more formats like .caj?

### ISSUE THREAD

**Issue by htyxyt** [giorginolab/zotfile_doctor#10]
In China, people usually download Chinese documents from [CNKI](https://www.cnki.net/).
These documents somtimes are in .caj format, not .pdf format.
So it would be better if this script can support .caj format.
Furthermore, in fact, Zotfile supports many formats like .pdf .doc .docx .txt .rtf .djvu.
Although some formats are less used,  it would be better if this script can support more formats.

**Comment by tonigi** [comment]
I guess support should be added to zotfile itself.

**Comment by northword** [comment]
https://github.com/northword/zotfile_doctor
增加了`.caj`格式支持。
其他几个格式懒得写了反正也用的不多😂
另外，茉莉花插件是可以下载带目录书签的pdf格式的，包括学位论文。
