### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by navid-mahmoudian** [giorginolab/zotfile_doctor#6]
Hello,

Thank you very much for providing such a code. I am not able to use the code because I get the following error:
```

File "zotfile_doctor.py", line 31, in get_db_set
    db_c = conn.execute(
sqlite3.OperationalError: database is locked
```

How can I fix this issue? 

My python version is: Python 3.8.2

Best,

**Comment by tonigi** [comment]
Zotero must be closed.
