### ISSUE TITLE
Why not opennign in read only mode?

### ISSUE THREAD

**Issue by navid-mahmoudian** [giorginolab/zotfile_doctor#7]
Hello,
Thank you again for this nice code. I was wondering to ask, why don't you open the database in read only mode inside `def get_db_set(db, d)` function with the following:

`conn = sqlite3.connect(db, uri=True)`

You just need to pass **uri=True** to the arguments of `sqlite3.connect`.
Thank you again for this useful code.

**Comment by tonigi** [comment]
That does not solve the issue, at least on my system.
