### ISSUE TITLE
all files in Zotfile directory missing from Zotero Database

### ISSUE THREAD

**Issue by moffat** [giorginolab/zotfile_doctor#8]
Hi,

I've been using zotfile_doctor very successfully for a while (thank you for your work!). I'm helping someone move to Zotero. She's using Zotfile and that's working fine, and has been cleaning up the database of duplicates. Of course, this is where zotfile_doctor would come handy.

However, when I run it on her library, *all* items in her library are listed as in the Zotfile directory but not in the database (i.e. if run with the -c option all files would be deleted). Any ideas of why would that happen?

**Comment by tonigi** [comment]
I can only make guesses: spaces or non-ascii characters in directory name?

**Comment by tonigi** [comment]
More guesses: "Zotfile custom location" is not absolute, or has a different case than the actual filesystem (which OSX allows).

**Comment by moffat** [comment]
Hi @tonigi 

Your second guess was correct. I was running this using relative paths, and the get_db_set function was returning an empty set. Once I used an absolute path, it worked. 

Thank you for getting back to me so quickly.

Best.
